/**
 * ENGS 32 — Environmental Science Question Bank
 * Items align with course PDFs (CvSU ENGS 32 Lec 5.4, 5.5, 6, 7).
 * Explanations cite external references where statutes/UN/IPCC apply.
 * RA 9003: officially APPROVED 26 Jan 2001 (Lawphil; short title "Act of 2000").
 */
window.ENVS_QB = [
  /* ========== LO7 KNOWLEDGE / COMPREHENSION ========== */
  {id:"lo7-01",lo:"LO7",level:"Knowledge",type:"mcq",text:"Solid waste is primarily a human concept because:",choices:[{ltr:"a",text:"Rocks cannot decompose"},{ltr:"b",text:"Biodegradation does not occur in nature"},{ltr:"c",text:"Humans classify discarded materials as unusable, while natural systems recycle matter"},{ltr:"d",text:"Only cities produce discards"}],ans:"c",expl:"Course PDF (Lec 5.4): waste is characterized as a concept unique to humans; natural systems reuse and recycle materials. Corroborates general biogeochemical cycling described in ecology texts (e.g., Molles 1999; Smith & Smith 1998).",refs:["CvSU Lec 5.4","Molles (1999) Ecology","Smith & Smith (1998) Elements of Ecology"]},
  {id:"lo7-02",lo:"LO7",level:"Knowledge",type:"mcq",text:"Which pair best matches “municipal waste” in the lecture?",choices:[{ltr:"a",text:"Mining tailings + fly ash only"},{ltr:"b",text:"Household refuse combined with commercial refuse"},{ltr:"c",text:"Hospital sharps only"},{ltr:"d",text:"Crop residues only"}],ans:"b",expl:"Lec 5.4 defines municipal waste as a combination of household and commercial refuse.",refs:["CvSU Lec 5.4"]},
  {id:"lo7-03",lo:"LO7",level:"Knowledge",type:"mcq",text:"Industrial solid waste arises mainly from:",choices:[{ltr:"a",text:"Office paperwork only"},{ltr:"b",text:"Manufacturing and industrial processes"},{ltr:"c",text:"Residential kitchens"},{ltr:"d",text:"Park maintenance only"}],ans:"b",expl:"Lec 5.4 source categories.",refs:["CvSU Lec 5.4"]},
  {id:"lo7-04",lo:"LO7",level:"Knowledge",type:"mcq",text:"Hazardous wastes (per lecture examples) may come from:",choices:[{ltr:"a",text:"Households only"},{ltr:"b",text:"Industries only"},{ltr:"c",text:"Households, industries, and hospitals containing toxic substances"},{ltr:"d",text:"Clean beach sand only"}],ans:"c",expl:"Lecture lists hazardous waste from households, industries and hospitals with toxic substances.",refs:["CvSU Lec 5.4"]},
  {id:"lo7-05",lo:"LO7",level:"Knowledge",type:"tf",text:"Biomedical or hospital waste may be infectious.",ans:true,expl:"Lecture classifies biomedical/hospital waste as infectious waste.",refs:["CvSU Lec 5.4"]},
  {id:"lo7-06",lo:"LO7",level:"Knowledge",type:"mcq",text:"Republic Act No. 9003 is officially cited as the:",choices:[{ltr:"a",text:"Clean Air Act of 1999"},{ltr:"b",text:"Ecological Solid Waste Management Act of 2000"},{ltr:"c",text:"Environmental Impact Statement Act"},{ltr:"d",text:"Renewable Energy Act"}],ans:"b",expl:"Republic Act No. 9003 short title is stated in the statute as the Ecological Solid Waste Management Act of 2000 (often dated by year of passage though approved into law in 2001). See Section 1, RA 9003 via Lawphil/Digest.ph.",refs:["RA 9003 §1 (Lawphil)","https://lawphil.net/statutes/repacts/ra2001/ra_9003_2001.html"]},
  {id:"lo7-07",lo:"LO7",level:"Knowledge",type:"mcq",text:"RA 9003 was approved on (official statute date):",choices:[{ltr:"a",text:"16 February 2001"},{ltr:"b",text:"26 January 2001"},{ltr:"c",text:"11 June 1978"},{ltr:"d",text:"26 January 2000"}],ans:"b",expl:"Your slide text gives an internal course date; the official Republic Act header shows approval 26 January 2001. Always prefer primary statute text for exams.",refs:["RA 9003 header (Lawphil)","CvSU Lec 5.4 (verify against statute)"]},
  {id:"lo7-08",lo:"LO7",level:"Comprehension",type:"mcq",text:"A policy goal explicitly declared in RA 9003 includes:",choices:[{ltr:"a",text:"Banning all plastics worldwide"},{ltr:"b",text:"Adopting a systematic, comprehensive, ecological SWM program ensuring protection of public health and the environment"},{ltr:"c",text:"Nationalizing all junk shops"},{ltr:"d",text:"Eliminating recycling"}],ans:"b",expl:"RA 9003 Sec. 2 Declaration of Policies (Digest.ph / Lawphil) lists protection of public health and environment and environmentally sound resource use.",refs:["RA 9003 §2","https://www.digest.ph/laws/an-act-providing-for-an-ecological-solid-waste-management-program"]},
  {id:"lo7-09",lo:"LO7",level:"Knowledge",type:"mcq",text:"Institutions emphasized under RA 9003 in the lecture include:",choices:[{ltr:"a",text:"NSWMC, NEC, and local SWMBs"},{ltr:"b",text:"Only the Barangay Captain"},{ltr:"c",text:"UN Security Council"},{ltr:"d",text:"World Bank only"}],ans:"a",expl:"Lec 5.4: NSWMC, National Ecology Center, Solid Waste Management Boards.",refs:["CvSU Lec 5.4","RA 9003 (institutional mechanisms in law)"]},
  {id:"lo7-10",lo:"LO7",level:"Knowledge",type:"tf",text:"The lecture cites ~74% of Metro Manila waste as coming from households (slide data).",ans:true,expl:"NSWMC-sourced figures in Lec 5.4 slides; verify current NSWMC reports for updated statistics.",refs:["CvSU Lec 5.4","NSWMC (Philippines)"]},
  {id:"lo7-11",lo:"LO7",level:"Knowledge",type:"mcq",text:"Climate (as defined in Lec 5.5) is best described as:",choices:[{ltr:"a",text:"Current wind speed at noon"},{ltr:"b",text:"Long-term average weather patterns, often discussed over ~30-year periods"},{ltr:"c",text:"A single storm event"},{ltr:"d",text:"Daily newspaper forecast"}],ans:"b",expl:"WMO/IPCC use ~30-year climatological reference periods; lecture aligns with this convention.",refs:["CvSU Lec 5.5","IPCC AR6 WGI Annex (climatological periods)"]},
  {id:"lo7-12",lo:"LO7",level:"Comprehension",type:"mcq",text:"Weather differs from climate because weather is:",choices:[{ltr:"a",text:"Always 30 years"},{ltr:"b",text:"Short-term atmospheric conditions at a place and time"},{ltr:"c",text:"Identical to climate"},{ltr:"d",text:"Only about humidity"}],ans:"b",expl:"Standard distinction in atmospheric science and repeated in Lec 5.5.",refs:["CvSU Lec 5.5","Ahrens & others (meteorology texts); IPCC glossaries"]},
  {id:"lo7-13",lo:"LO7",level:"Knowledge",type:"mcq",text:"The lecture highlights which greenhouse gases as most closely tied to global warming?",choices:[{ltr:"a",text:"Nitrogen and argon"},{ltr:"b",text:"Oxygen and hydrogen only"},{ltr:"c",text:"Carbon dioxide and methane"},{ltr:"d",text:"Helium only"}],ans:"c",expl:"Lec 5.5 explicitly foregrounds CO₂ and CH₄; IPCC WGI details radiative forcing contributions from multiple gases.",refs:["CvSU Lec 5.5","IPCC (2018 SR1.5 / AR6)"]},
  {id:"lo7-14",lo:"LO7",level:"Comprehension",type:"mcq",text:"The ice–albedo feedback described in the lecture means:",choices:[{ltr:"a",text:"More ice always cools the core"},{ltr:"b",text:"Melting reflective ice exposes darker ocean that absorbs more solar energy, amplifying warming"},{ltr:"c",text:"Oceans become white"},{ltr:"d",text:"Clouds disappear entirely"}],ans:"b",expl:"Physical feedback common in climate science courses and in Lec 5.5 slide narrative.",refs:["CvSU Lec 5.5","IPCC WGI feedbacks"]},
  {id:"lo7-15",lo:"LO7",level:"Knowledge",type:"mcq",text:"The Paris Agreement long-term temperature goal as noted in the lecture:",choices:[{ltr:"a",text:"Hold warming well below 2°C and pursue 1.5°C"},{ltr:"b",text:"Allow 5°C rise"},{ltr:"c",text:"No numeric target"},{ltr:"d",text:"Cool to pre-industrial in 5 years"}],ans:"a",expl:"UNFCCC Paris Agreement Article 2; lecture mirrors this framing.",refs:["CvSU Lec 5.5","UNFCCC Paris Agreement"]},
  {id:"lo7-16",lo:"LO7",level:"Knowledge",type:"tf",text:"Nationally Determined Contributions (NDCs) under the Paris Agreement are updated on a five-year cycle (lecture).",ans:true,expl:"Paris Agreement Articles 4 & 14 outline global stocktake and successive NDC cycles; lecture states 5-year updates.",refs:["CvSU Lec 5.5","UNFCCC Paris Agreement"]},
  {id:"lo7-17",lo:"LO7",level:"Comprehension",type:"mcq",text:"Deforestation contributes to climate forcing mainly by:",choices:[{ltr:"a",text:"Increasing planetary albedo uniformly"},{ltr:"b",text:"Releasing carbon stored in biomass and reducing future uptake"},{ltr:"c",text:"Eliminating oxygen from the atmosphere"},{ltr:"d",text:"Stopping all rainfall"}],ans:"b",expl:"Standard carbon-cycle explanation; appears in IPCC AFOLU chapters and Lec 5.5 causes.",refs:["CvSU Lec 5.5","IPCC AR6 WGIII / WGI"]},
  {id:"lo7-18",lo:"LO7",level:"Knowledge",type:"mcq",text:"Solid waste management (lecture definition) is the systematic control of generation through:",choices:[{ltr:"a",text:"Only landfilling"},{ltr:"b",text:"Storage, collection, transport, separation, processing, recycling, recovery, and disposal"},{ltr:"c",text:"Open burning only"},{ltr:"d",text:"Export only"}],ans:"b",expl:"Verbatim concept from Lec 5.4 waste management definition.",refs:["CvSU Lec 5.4"]},

  /* LO8 */
  {id:"lo8-01",lo:"LO8",level:"Comprehension",type:"mcq",text:"In the General Trias study cited, waste mass correlated most strongly with:",choices:[{ltr:"a",text:"Family size (highly significant)"},{ltr:"b",text:"Educational attainment (highly significant)"},{ltr:"c",text:"Distance to moon"},{ltr:"d",text:"Barangay name length"}],ans:"a",expl:"Slide: family size highly significant; income & occupation significant; educational attainment NOT significant.",refs:["CvSU Lec 5.4"]},
  {id:"lo8-02",lo:"LO8",level:"Synthesis",type:"mcq",text:"Integrating plastics in rivers (lecture statistic) with environmental crises best supports which statement?",choices:[{ltr:"a",text:"Plastics cannot float"},{ltr:"b",text:"Poor disposal → water pollution & drainage blockage → compounded flood/ecosystem risks"},{ltr:"c",text:"Rivers sanitize plastics"},{ltr:"d",text:"Only climate matters"}],ans:"b",expl:"Synthesis bridging waste + pollution concerns; aligns with pollution pathway narratives in Nathanson & Katyal-type texts.",refs:["CvSU Lec 5.4","Nathanson (1997) Basic Environmental Technology","Katyal & Satake (2006)"]},
  {id:"lo8-03",lo:"LO8",level:"Comprehension",type:"tf",text:"Higher per-capita waste in higher-income groups (2016 lecture comparison) implies consumption-linked waste intensity.",ans:true,expl:"Slides compare 0.5 vs 0.34 kg/cap/day — interpret as lifestyle/consumption link (standard MSW economics literature).",refs:["CvSU Lec 5.4","Mihelcic & Zimmerman (2014) sustainability & consumption"]},

  /* LO9 */
  {id:"lo9-01",lo:"LO9",level:"Analysis",type:"mcq",text:"An environmental \"impact\" in EIA equals:",choices:[{ltr:"a",text:"The EMP budget"},{ltr:"b",text:"Change from the baseline caused by the activity"},{ltr:"c",text:"ECC validity period"},{ltr:"d",text:"Project ribbon-cutting date"}],ans:"b",expl:"Lec 6: impact defined as deviation from baseline due to activity—standard textbook phrasing matches Canter, Morris-Jones, WB/ADB guidance.",refs:["CvSU Lec 6","ADB / World Bank Environmental Assessment Sourcebooks"]},
  {id:"lo9-02",lo:"LO9",level:"Analysis",type:"mcq",text:"Baseline conditions should account for:",choices:[{ltr:"a",text:"A single instantaneous snapshot ignoring variability"},{ltr:"b",text:"Temporal variability and trends, not only a snapshot"},{ltr:"c",text:"Investor moods"},{ltr:"d",text:"Stock prices only"}],ans:"b",expl:"Lecture explicitly warns baseline is a process with variability/trend.",refs:["CvSU Lec 6"]},
  {id:"lo9-03",lo:"LO9",level:"Knowledge",type:"tf",text:"EIA integrates biophysical, social/cultural, health, economic/fiscal dimensions (among others).",ans:true,expl:"Integrated dimensions listed in Lec 6 slides.",refs:["CvSU Lec 6"]},
  {id:"lo9-04",lo:"LO9",level:"Analysis",type:"mcq",text:"Why focus on \"most significant impacts\"?",choices:[{ltr:"a",text:"Infinite time/resources"},{ltr:"b",text:"Time and resources limit depth; prioritize significant effects"},{ltr:"c",text:"Minor impacts always zero"},{ltr:"d",text:"Law forbids matrices"}],ans:"b",expl:"Slide rationale; matches screening/scoping practice in Philippine EMB guidelines.",refs:["CvSU Lec 6","DENR-EMB EIA procedural materials"]},

  /* LO10 */
  {id:"lo10-01",lo:"LO10",level:"Knowledge",type:"mcq",text:"Presidential Decree No. 1586 (Philippines) established:",choices:[{ltr:"a",text:"The Renewable Portfolio Standard"},{ltr:"b",text:"The Philippine Environmental Impact Statement System"},{ltr:"c",text:"RA 9003"},{ltr:"d",text:"Clean Water Act of the USA"}],ans:"b",expl:"PD 1586 (June 11, 1978) institutes the Philippine EIS System—see Lawphil/Chan Robles/ADB law brief.",refs:["PD 1586","https://lawphil.net/statutes/presdecs/pd1978/pd_1586_1978.html"]},
  {id:"lo10-02",lo:"LO10",level:"Knowledge",type:"mcq",text:"PD 1151 requires EIS submission for proposals that:",choices:[{ltr:"a",text:"Never affect environment"},{ltr:"b",text:"May significantly affect environmental quality"},{ltr:"c",text:"Only build schools"},{ltr:"d",text:"Are under ₱50 000"}],ans:"b",expl:"Lec 6 legal bases; aligns with wording of Presidential Decree 1151 (Philippine Environmental Policy).",refs:["CvSU Lec 6","PD 1151"]},
  {id:"lo10-03",lo:"LO10",level:"Comprehension",type:"mcq",text:"Projects classified as Category D in DENR screening typology:",choices:[{ltr:"a",text:"Always need an ECC regardless"},{ltr:"b",text:"Presumed unlikely to cause significant adverse impact and are not covered by PEISS for ECC requirement"},{ltr:"c",text:"Must build in ECAs only"},{ltr:"d",text:"Are hazardous by default"}],ans:"b",expl:"Matches slide Category D narrative; aligns with DENR/EMB online orientation materials cited in bibliography (DOE & DENR EIS orientation PDF).",refs:["CvSU Lec 6","DOE/DENR EIS Orientation PDF"]},
  {id:"lo10-04",lo:"LO10",level:"Knowledge",type:"mcq",text:"An ECC is issued by DENR–EMB and certifies (lecture gist):",choices:[{ltr:"a",text:"Ignoring environmental laws"},{ltr:"b",text:"Proponent complied with PEISS requirements subject to stipulated conditions minimizing adverse effects"},{ltr:"c",text:"No monitoring needed"},{ltr:"d",text:"Permanent exemption from all laws"}],ans:"b",expl:"Lecture definition; aligns with ECC descriptions in DENR trainer PDFs.",refs:["CvSU Lec 6","DENR-EMB ECC guidance summaries"]},
  {id:"lo10-05",lo:"LO10",level:"Comprehension",type:"tf",text:"Slides state ECC expires if project is not implemented within five years from issuance.",ans:true,expl:"Repeated in DENR ECC validity guidance excerpts (trainer PDFs); also in lecture.",refs:["CvSU Lec 6","WEAP-Phil PD 1586 / ECC guideline excerpt"]},

  /* LO11 */
  {id:"lo11-01",lo:"LO11",level:"Comprehension",type:"mcq",text:"The FIRST major procedural step in the lecture’s EIA sequence is:",choices:[{ltr:"a",text:"Post-audit only"},{ltr:"b",text:"Scoping"},{ltr:"c",text:"Sell shares"},{ltr:"d",text:"Groundbreaking"}],ans:"b",expl:"Lec 6 lists scoping as step 1.",refs:["CvSU Lec 6"]},
  {id:"lo11-02",lo:"LO11",level:"Analysis",type:"mcq",text:"Impact prediction approaches in the lecture include:",choices:[{ltr:"a",text:"Astrology and tarot"},{ltr:"b",text:"Expert judgment, comparisons, on-site experiments, mathematical models"},{ltr:"c",text:"Only coin toss"},{ltr:"d",text:"Guessing baseline color"}],ans:"b",expl:"Explicit list in Lec 6; consistent with impact prediction methods in Intro to Environmental Engineering references.",refs:["CvSU Lec 6","Masters (1998)","Davis & Cornwell (2013)"]},
  {id:"lo11-03",lo:"LO11",level:"Comprehension",type:"tf",text:"Environmental Management Plan (EMP) includes mitigation and monitoring elements.",ans:true,expl:"Lecture EMP bullet points (enhance positive, reduce negative, monitoring, reporting).",refs:["CvSU Lec 6"]},

  /* LO12 */
  {id:"lo12-01",lo:"LO12",level:"Knowledge",type:"mcq",text:"The Brundtland Commission (1987) defined sustainable development as development that:",choices:[{ltr:"a",text:"Maximizes present profit only"},{ltr:"b",text:"Meets present needs without compromising future generations’ ability to meet their own needs"},{ltr:"c",text:"Stops all industry"},{ltr:"d",text:"Bans renewable energy"}],ans:"b",expl:"UN World Commission on Environment and Development, Our Common Future (1987)—verbatim definition used in lecture.",refs:["CvSU Lec 7","UN WCED (1987) Our Common Future"]},
  {id:"lo12-02",lo:"LO12",level:"Knowledge",type:"mcq",text:"How many Sustainable Development Goals (SDGs) are in the UN framework cited in lecture?",choices:[{ltr:"a",text:"10"},{ltr:"b",text:"15"},{ltr:"c",text:"17"},{ltr:"d",text:"25"}],ans:"c",expl:"United Nations publishes 17 SDGs (2015); lecture notes 17 interlinked goals.",refs:["CvSU Lec 7","https://sdgs.un.org/goals"]},
  {id:"lo12-03",lo:"LO12",level:"Analysis",type:"tf",text:"Achieving sustainability requires balancing economic development, environmental protection, and social well-being (triple-pillar framing in lecture).",ans:true,expl:"Echoes Elkington-style triple bottom line and UN sustainable development pillar discourse; aligns with lecture text.",refs:["CvSU Lec 7","UN SDGs materials","Kaneko et al. (2014) sustainable living narratives"]},

  /* LO13 */
  {id:"lo13-01",lo:"LO13",level:"Knowledge",type:"mcq",text:"The Human Development Index (HDI) composite includes longevity, education, and:",choices:[{ltr:"a",text:"Military spending rank"},{ltr:"b",text:"Income (GNI per capita)"},{ltr:"c",text:"Instagram followers"},{ltr:"d",text:"Coastline length"}],ans:"b",expl:"UNDP HDI methodology; lecture lists life expectancy, education, income.",refs:["CvSU Lec 7","UNDP HDR / HDI"]},
  {id:"lo13-02",lo:"LO13",level:"Comprehension",type:"mcq",text:"Cleaner production focuses on:",choices:[{ltr:"a",text:"Painting logos only"},{ltr:"b",text:"Improving environmental performance of processes—reducing materials/energy/emissions/wastewater/noise/waste heat"},{ltr:"c",text:"More packaging"},{ltr:"d",text:"Dumping untreated effluent"}],ans:"b",expl:"Matches Lec 7 cleaner production description; parallels UNEP cleaner production terminology.",refs:["CvSU Lec 7","UNEP Cleaner Production","Mihelcic & Zimmerman (2014)"]},
  {id:"lo13-03",lo:"LO13",level:"Knowledge",type:"mcq",text:"Which is a renewable energy example from the lecture list?",choices:[{ltr:"a",text:"Anthropogenic peat from ancient swamp (non-renewable in practice)"},{ltr:"b",text:"Geothermal"},{ltr:"c",text:"Bituminous coal"},{ltr:"d",text:"Low-grade shale oil"}],ans:"b",expl:"Lecture lists solar, wind, hydro, biomass, geothermal as renewables.",refs:["CvSU Lec 7"]},
  {id:"lo13-04",lo:"LO13",level:"Comprehension",type:"mcq",text:"Ecological footprint measures:",choices:[{ltr:"a",text:"Only IQ"},{ltr:"b",text:"Bioproductive land/water demand implied by consumption relative to biocapacity"},{ltr:"c",text:"Stock index"},{ltr:"d",text:"Noise in dB only"}],ans:"b",expl:"Wackernagel/Rees footprint concept; summarized in Measuring Sustainable Development UN note referenced in lecture references.",refs:["CvSU Lec 7","UN (2009) Measuring Sustainable Development pdf","Hoekstra & Wackernagel literature"]},

  /* More LO7 drills */
  {id:"lo7-19",lo:"LO7",level:"Knowledge",type:"tf",text:"Agricultural waste includes materials from harvesting or cropping activities.",ans:true,expl:"Lec 5.4 source list.",refs:["CvSU Lec 5.4"]},
  {id:"lo7-20",lo:"LO7",level:"Knowledge",type:"mcq",text:"Commercial waste in the lecture comes from activities that:",choices:[{ltr:"a",text:"Always smelt metal"},{ltr:"b",text:"Do not necessarily manufacture a product (e.g., stores, offices)"},{ltr:"c",text:"Only fish"},{ltr:"d",text:"Only generate nuclear power"}],ans:"b",expl:"Lec 5.4 definition.",refs:["CvSU Lec 5.4"]},
  {id:"lo10-06",lo:"LO10",level:"Knowledge",type:"mcq",text:"Environmentally Critical Areas in the lecture include:",choices:[{ltr:"a",text:"Only shopping malls"},{ltr:"b",text:"Watershed reserves, wildlife sanctuaries, coral reefs, mangroves, aquifer recharge areas (among others)"},{ltr:"c",text:"Desert only"},{ltr:"d",text:"Indoor offices"}],ans:"b",expl:"Illustrative list from Lec 6 ECA slide; full lists in PP 2146 as amended—verify exact classification for legal exams.",refs:["CvSU Lec 6","PP 2146 / DENR lists"]},
  {id:"lo10-07",lo:"LO10",level:"Knowledge",type:"mcq",text:"Major dams and major power plants appear in slides as examples of:",choices:[{ltr:"a",text:"Category D only"},{ltr:"b",text:"Environmentally Critical Projects (ECPs)"},{ltr:"c",text:"Projects exempt from all laws"},{ltr:"d",text:"Residential compost"}],ans:"b",expl:"Lec 6 ECP infrastructure examples.",refs:["CvSU Lec 6"]},
  {id:"lo11-04",lo:"LO11",level:"Comprehension",type:"mcq",text:"Spatial scoping in EIA can include:",choices:[{ltr:"a",text:"Only the proponent’s office"},{ltr:"b",text:"Direct impact area, primary/secondary zones, regional impact zone"},{ltr:"c",text:"Only outer space"},{ltr:"d",text:"No boundaries"}],ans:"b",expl:"Lec 6 scoping bullet points.",refs:["CvSU Lec 6"]},
  {id:"lo11-05",lo:"LO11",level:"Analysis",type:"mcq",text:"Impact evaluation significance may consider:",choices:[{ltr:"a",text:"Only paint color"},{ltr:"b",text:"Statistical likelihood/extent, ecological organization level, social importance"},{ltr:"c",text:"Zodiac"},{ltr:"d",text:"CPU clock speed"}],ans:"b",expl:"Lecture lists statistical, ecological, social importance dimensions.",refs:["CvSU Lec 6"]},
  {id:"lo9-05",lo:"LO9",level:"Analysis",type:"tf",text:"An activity (e.g., major road) can be decomposed into multiple concrete actions (survey, grading, culvert construction).",ans:true,expl:"Activity vs actions hierarchy in Lec 6.",refs:["CvSU Lec 6"]},
  {id:"lo13-05",lo:"LO13",level:"Knowledge",type:"mcq",text:"Circular economy (lecture) emphasizes:",choices:[{ltr:"a",text:"Single-use everything"},{ltr:"b",text:"Keeping materials in use via reduce/reuse/recycle and cutting finite resource demand"},{ltr:"c",text:"Linear take-make-waste only"},{ltr:"d",text:"Landfill-only society"}],ans:"b",expl:"Lec 7 circular economy bullets; aligns with EU / UNEP circular economy literature.",refs:["CvSU Lec 7","UNEP / EU Circular Economy Action Plan (context)"]},
  {id:"lo12-04",lo:"LO12",level:"Comprehension",type:"mcq",text:"Environmental Performance Index (EPI) in lecture is described as:",choices:[{ltr:"a",text:"A video game leaderboard"},{ltr:"b",text:"A composite ranking of environmental sustainability performance across countries using multiple indicators"},{ltr:"c",text:"GDP only"},{ltr:"d",text:"Soil taxonomy"}],ans:"b",expl:"Yale–Columbia EPI project framing matches lecture wording.",refs:["CvSU Lec 7","https://epi.yale.edu/"]},

  {id:"lo7-21",lo:"LO7",level:"Knowledge",type:"tf",text:"The greenhouse effect refers to trapping of heat by atmospheric gases.",ans:true,expl:"IPCC and standard meteorology texts define greenhouse gases as those that absorb and emit infrared radiation, warming the climate system.",refs:["CvSU Lec 5.5","IPCC WGI glossary"]},
  {id:"lo7-22",lo:"LO7",level:"Comprehension",type:"mcq",text:"Ozone in photochemical smog formed from NOx and VOC precursors is typically classified as:",choices:[{ltr:"a",text:"A primary pollutant emitted directly by stacks"},{ltr:"b",text:"A secondary pollutant formed in the atmosphere"},{ltr:"c",text:"Not related to air quality"},{ltr:"d",text:"Only dissolved in groundwater"}],ans:"b",expl:"Secondary pollutants form through atmospheric chemistry; textbook air-pollution chapters (e.g., Davis & Cornwell; Nathanson) contrast primary vs secondary species.",refs:["CvSU Lec 5.5","Nathanson","Davis & Cornwell"]},
  {id:"lo7-23",lo:"LO7",level:"Knowledge",type:"tf",text:"Methane has a shorter atmospheric lifetime than CO₂ but strong warming influence per tonne on multi-decade horizons.",ans:true,expl:"IPCC AR6 documents CH₄’s relatively short decay versus CO₂’s long-lived climate effect; GWP values weight this difference.",refs:["IPCC AR6 WGI Ch.5 / Ch.7"]},
  {id:"lo9-06",lo:"LO9",level:"Knowledge",type:"mcq",text:"In Philippines EIA practice, the core intent is to foresee environmental consequences and prescribe mitigation:",choices:[{ltr:"a",text:"Only after abandonment"},{ltr:"b",text:"Before irrevocable commitments, supporting informed decisions"},{ltr:"c",text:"Without any public input"},{ltr:"d",text:"Only for foreign-funded projects"}],ans:"b",expl:"Matches doctrinal summaries of IA (ADB/World Bank safeguards) and national PEISS procedural goal.",refs:["CvSU Lec 6","ADB Environmental Assessment Guidelines"]},
  {id:"lo10-08",lo:"LO10",level:"Knowledge",type:"tf",text:"The Philippine Environmental Impact Statement System was established under Presidential Decree No. 1586 (1978).",ans:true,expl:"Lawphil official header: PD No. 1586 — Philippine Environmental Impact Statement System, 11 June 1978.",refs:["https://lawphil.net/statutes/presdecs/pd1978/pd_1586_1978.html"]},
  {id:"lo11-06",lo:"LO11",level:"Knowledge",type:"mcq",text:"“Review of predictions” in the lecture’s EIA sequence serves to:",choices:[{ltr:"a",text:"Delete the baseline"},{ltr:"b",text:"Check technical defensibility of forecasted impacts"},{ltr:"c",text:"Replace ECC with tax forms"},{ltr:"d",text:"Cancel monitoring"}],ans:"b",expl:"Quality-assurance step common in EIA texts and Lec 6 methodology.",refs:["CvSU Lec 6","Glasson et al. Introduction to EIA"]},
  {id:"lo11-07",lo:"LO11",level:"Comprehension",type:"tf",text:"Public participation can inform scoping and improve acceptance of mitigation measures.",ans:true,expl:"IA best practice and Philippine procedures incorporate consultation; IAIA principles highlight transparency.",refs:["CvSU Lec 6","IAIA"]},
  {id:"lo12-05",lo:"LO12",level:"Knowledge",type:"mcq",text:"Intergenerational equity in sustainability means:",choices:[{ltr:"a",text:"Future generations have no rights"},{ltr:"b",text:"Today’s choices should not foreclose quality of life for future generations"},{ltr:"c",text:"Only GDP growth matters"},{ltr:"d",text:"Ban all fossil use tomorrow without transition"}],ans:"b",expl:"Brundtland report frames needs of present and future generations; UN SD discourse repeats this.",refs:["UN WCED (1987)","CvSU Lec 7"]},
  {id:"lo12-06",lo:"LO12",level:"Knowledge",type:"mcq",text:"Which statement about UN SDG 13 is correct?",choices:[{ltr:"a",text:"SDG 13 is “Climate Action”"},{ltr:"b",text:"There is no climate-related SDG"},{ltr:"c",text:"SDG 13 is exclusively about marine plastics"},{ltr:"d",text:"SDGs were adopted in 1992 only"}],ans:"a",expl:"UN lists Goal 13 as Climate Action (adopted 2015 framework).",refs:["https://sdgs.un.org/goals/goal13"]},
  {id:"lo13-06",lo:"LO13",level:"Comprehension",type:"mcq",text:"The Multidimensional Poverty Index bundles deprivations across:",choices:[{ltr:"a",text:"Only income"},{ltr:"b",text:"Health, education, and living standards (OPHI/UNDP methodology)"},{ltr:"c",text:"Stock tickers"},{ltr:"d",text:"Satellite TV channels"}],ans:"b",expl:"UNDP/OPHI MPI documentation defines overlapping deprivation in multiple dimensions.",refs:["CvSU Lec 7","UNDP MPI"]},
  {id:"lo13-07",lo:"LO13",level:"Knowledge",type:"tf",text:"The Gender Inequality Index (GII) is a composite gender-disparity measure published in UNDP Human Development Reports.",ans:true,expl:"UNDP HDR technical notes define GII components (reproductive health, empowerment, labor market).",refs:["CvSU Lec 7","UNDP GII"]},
  {id:"lo8-04",lo:"LO8",level:"Comprehension",type:"mcq",text:"Leachate from municipal landfills is mainly a risk because it can:",choices:[{ltr:"a",text:"Improve Wi-Fi"},{ltr:"b",text:"Transport dissolved contaminants to groundwater or surface water"},{ltr:"c",text:"Increase stratospheric ozone"},{ltr:"d",text:"Eliminate methane"}],ans:"b",expl:"Solid-waste engineering references describe leachate collection/treatment to protect water resources.",refs:["CvSU Lec 5.4","Masters Environmental Engineering"]},
  {id:"lo8-05",lo:"LO8",level:"Knowledge",type:"tf",text:"RA 9003 policy favors systematic ecological SWM (segregation, reduction, recycling) over uncontrolled dumping where alternatives exist.",ans:true,expl:"RA 9003 Sec. 2 policies (Lawphil) emphasize protection of health/environment and ecologically sound resource use; prohibited acts are listed later in the Act.",refs:["RA 9003 §2","Lawphil RA 9003"]},
  {id:"lo10-09",lo:"LO10",level:"Comprehension",type:"mcq",text:"A Certificate of Non-Coverage (CNC) generally indicates:",choices:[{ltr:"a",text:"Proponent must still obtain an ECC in all cases"},{ltr:"b",text:"The project is not covered by the ECC requirement under the rules evaluated"},{ltr:"c",text:"Project failed EIA"},{ltr:"d",text:"Automatic closure of business"}],ans:"b",expl:"EMB processing terminology; always cross-check current DAO/MCs because procedural labels evolve.",refs:["CvSU Lec 6","DENR-EMB CNC guidance"]},
];

window.ENVS_ESSAYS = [
  {id:"e1",lo:"LO8",level:"Synthesis",title:"Urban waste & environmental crises",prompt:"Integrate RA 9003 instruments with at least TWO environmental crisis dimensions (pollution, resource strain, vulnerability) using lecture waste statistics as evidence.",guide:["Cite NSWMC/MM or national kg/cap/day only as in slides","Explain segregation + SWM pillars","Avoid inventing unpublished numbers"]},
  {id:"e2",lo:"LO9",level:"Analysis",title:"Baseline → Impact logic",prompt:"Explain how baseline variability affects impact significance for a hypothetical quarry in an ECA.",guide:["Define baseline vs impact","Give one biophysical metric + one social","Link to mitigation need"]},
  {id:"e3",lo:"LO10",level:"Analysis",title:"ECC vs CNC",prompt:"Contrast when an ECC versus CNC pathway applies using Categories A–D.",guide:["Reference PD 1586 / DENR categorization framing","ECC conditions & validity rules from lecture"]},
  {id:"e4",lo:"LO11",level:"Synthesis",title:"EIA procedure map",prompt:"Sequence scoping→baseline→prediction→evaluation→EMP→review→ECC→monitoring and tie each step to ONE decision-maker need.",guide:["210–400 words typical"]},
  {id:"e5",lo:"LO12",level:"Analysis",title:"WCED definition stress-test",prompt:"Argue whether high-carbon business-as-usual growth meets WCED sustainability; cite intergenerational equity.",guide:["Define Brundtland","Use planetary boundaries discourse cautiously"]},
  {id:"e6",lo:"LO13",level:"Synthesis",title:"Measures & instruments",prompt:"Compare HDI versus Ecological Footprint as dashboards; link one SDG each to renewables and cleaner production.",guide:["Strengths/limit each indicator"]},
];
